apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-demo
  labels:
    env: qa
spec:
  replicas: 3
  selector:
    matchLabels:
      env: qa
  template:
    metadata:
      labels:
        env: qa
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
